//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S14Lab_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public string Placa { get; set; }
        public int idOficina { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int nAsientos { get; set; }
        public int FabYear { get; set; }
    
        public virtual Oficina Oficina { get; set; }
    }
}
